In [133]:
import pandas as pd
import numpy as np

station = "mrlb"
data = pd.read_csv(f"../data/{station}/metars.csv", index_col=0)
data.head()

,date,wind_dir_deg,wind_speed_kt,wind_gust_kt,visibility_m,is_cavok,weather_1,weather_2,weather_3,is_ceiling,temp_c,dewpoint_c,pressure_inhg
0,2005-01-01 01:00,80.0,15.0,NaN,10000.0,0,NaN,NaN,NaN,0,27.0,19.0,29.84
1,2005-01-01 13:00,30.0,4.0,NaN,10000.0,0,NaN,NaN,NaN,0,23.0,20.0,29.90
2,2005-01-01 14:00,50.0,4.0,NaN,10000.0,0,NaN,NaN,NaN,0,27.0,20.0,29.92
3,2005-01-01 15:00,60.0,16.0,NaN,10000.0,0,NaN,NaN,NaN,0,30.0,20.0,29.94
4,2005-01-01 16:00,70.0,14.0,NaN,10000.0,0,NaN,NaN,NaN,0,31.0,20.0,29.93

In [132]:
df = data[["date", "visibility_m", "weather_1", "weather_2", "weather_3"]]
df = df.query("visibility_m < 8000.0")
df.head()

                  date  visibility_m weather_1 weather_2 weather_3
1680  2005-05-16 17:00        1500.0        RA       NaN       NaN
1681  2005-05-16 18:00        4000.0        RA       NaN       NaN
1682  2005-05-16 19:00        2500.0        RA       NaN       NaN
1732  2005-05-20 18:00        5000.0        RA       NaN       NaN
1734  2005-05-20 20:00        3000.0        RA       NaN       NaN

In [119]:
df['precipitation'] = 0
df.loc[df['weather_1'].astype(str).str.contains('RA|DZ', regex=True), 'precipitation'] = 1
df.loc[df['weather_2'].astype(str).str.contains('RA|DZ', regex=True), 'precipitation'] = 1
df.loc[df['weather_3'].astype(str).str.contains('RA|DZ', regex=True), 'precipitation'] = 1
df.head(50)

,date,visibility_m,weather_1,weather_2,weather_3,precipitation
1680,2005-05-16 17:00,1500.0,RA,NaN,NaN,1
1681,2005-05-16 18:00,4000.0,RA,NaN,NaN,1
1682,2005-05-16 19:00,2500.0,RA,NaN,NaN,1
1732,2005-05-20 18:00,5000.0,RA,NaN,NaN,1
1734,2005-05-20 20:00,3000.0,RA,NaN,NaN,1
1736,2005-05-20 22:00,7000.0,-RA,NaN,NaN,1
1751,2005-05-22 12:00,200.0,FG,NaN,NaN,0
1752,2005-05-22 13:00,3000.0,BR,NaN,NaN,0
1764,2005-05-23 12:00,1000.0,BR,NaN,NaN,0
1801,2005-05-26 12:00,3000.0,BR,NaN,NaN,0
1814,2005-05-27 12:00,2000.0,BR,NaN,NaN,0
1925,2005-06-05 00:00,1500.0,RA,NaN,NaN,1
1955,2005-06-07 16:00,5000.0,-RA,NaN,NaN,1
1958,2005-06-07 19:00,4000.0,-RA,NaN,NaN,1
1959,2005-06-07 20:00,3000.0,-RA,BR,NaN,1
1988,2005-06-10 13:00,3000.0,-RA,BR,NaN,1
2000,2005-06-11 12:00,2000.0,-RA,BR,NaN,1
2001,2005-06-11 13:00,5000.0,RA,NaN,NaN,1
2008,2005-06-11 20:00,3000.0,-RA,NaN,NaN,1
2035,2005-06-14 12:00,400.0,FG,NaN,NaN,0
2036,2005-06-14 13:00,1000.0,BR,NaN,NaN,0
2084,2005-06-18 13:00,2000.0,BR,NaN,NaN,0
2085,2005-06-18 14:00,5000.0,BR,NaN,NaN,0
2093,2005-06-18 22:00,3000.0,-TSRA,NaN,NaN,1
2096,2005-06-19 12:00,500.0,FG,NaN,NaN,0
2097,2005-06-19 13:00,500.0,FG,NaN,NaN,0
2152,2005-06-23 20:00,500.0,+RA,NaN,NaN,1
2153,2005-06-23 21:00,2000.0,-RA,BR,NaN,1
2157,2005-06-24 12:00,4000.0,BR,NaN,NaN,0
2170,2005-06-25 12:00,1500.0,BR,NaN,NaN,0
2182,2005-06-26 12:00,100.0,FG,NaN,NaN,0
2183,2005-06-26 13:00,500.0,FG,NaN,NaN,0
2190,2005-06-26 20:00,7000.0,VCSH,NaN,NaN,0
2192,2005-06-26 22:00,3000.0,RA,BR,NaN,1
2195,2005-06-27 12:00,200.0,FG,NaN,NaN,0
2196,2005-06-27 13:00,2000.0,BR,NaN,NaN,0
2216,2005-06-28 21:00,2500.0,-TSRA,NaN,NaN,1
2218,2005-06-28 23:00,6000.0,-RA,NaN,NaN,1
2223,2005-06-29 15:00,3000.0,RA,NaN,NaN,1
2332,2005-07-08 12:00,200.0,FG,NaN,NaN,0
2333,2005-07-08 13:00,500.0,FG,NaN,NaN,0
2377,2005-07-11 20:00,2000.0,RA,NaN,NaN,1
2445,2005-07-17 12:00,500.0,FG,NaN,NaN,0
2779,2005-08-13 20:00,5000.0,-RA,NaN,NaN,1
2844,2005-08-18 20:00,2000.0,-TSRA,NaN,NaN,1
2849,2005-08-19 12:00,600.0,FG,NaN,NaN,0
2899,2005-08-22 23:00,1000.0,TSRA,NaN,NaN,1
2929,2005-08-26 12:00,100.0,FG,NaN,NaN,0
2930,2005-08-26 13:00,400.0,FG,NaN,NaN,0
2937,2005-08-26 20:00,2000.0,RA,NaN,NaN,1

In [120]:
df.tail(50)

,date,visibility_m,weather_1,weather_2,weather_3,precipitation
124067,2025-10-12 12:33,1000.0,RA,NaN,NaN,1
124070,2025-10-12 15:00,5000.0,-RA,NaN,NaN,1
124071,2025-10-12 15:16,1000.0,RA,NaN,NaN,1
124072,2025-10-12 16:00,3000.0,RA,NaN,NaN,1
124073,2025-10-12 17:00,5000.0,-RA,NaN,NaN,1
124075,2025-10-12 19:00,7000.0,-RA,NaN,NaN,1
124123,2025-10-14 22:10,5000.0,+TSRA,BR,NaN,1
124124,2025-10-14 22:40,5000.0,TSRA,BR,NaN,1
124133,2025-10-15 12:00,100.0,FG,NaN,NaN,0
124134,2025-10-15 13:00,200.0,FG,NaN,NaN,0
124135,2025-10-15 13:20,5000.0,BR,NaN,NaN,0
124136,2025-10-15 14:00,7000.0,BCFG,NaN,NaN,0
124143,2025-10-15 19:17,3000.0,TSRA,NaN,NaN,1
124166,2025-10-16 18:07,3000.0,+TSRA,BR,NaN,1
124167,2025-10-16 18:18,5000.0,TSRA,BR,NaN,1
124173,2025-10-16 22:30,6000.0,RA,NaN,NaN,1
124174,2025-10-16 23:00,5000.0,RA,NaN,NaN,1
124175,2025-10-16 23:24,2000.0,+RA,NaN,NaN,1
124176,2025-10-17 00:00,2000.0,RA,NaN,NaN,1
124177,2025-10-17 00:00,2000.0,RA,NaN,NaN,1
124179,2025-10-17 01:00,6000.0,RA,NaN,NaN,1
124185,2025-10-17 12:00,1000.0,FG,NaN,NaN,0
124186,2025-10-17 12:09,3000.0,BCFG,NaN,NaN,0
124188,2025-10-17 13:21,5000.0,BR,NaN,NaN,0
124189,2025-10-17 14:00,6000.0,VCFG,NaN,NaN,0
124197,2025-10-17 20:49,5000.0,TSRA,NaN,NaN,1
124198,2025-10-17 21:00,2000.0,RA,NaN,NaN,1
124208,2025-10-18 05:00,4000.0,BR,NaN,NaN,0
124209,2025-10-18 06:00,3000.0,BR,NaN,NaN,0
124221,2025-10-18 21:08,800.0,RA,NaN,NaN,1
124236,2025-10-19 12:38,500.0,FG,NaN,NaN,0
124311,2025-10-22 22:00,5000.0,TSRA,NaN,NaN,1
124319,2025-10-23 05:00,3000.0,BR,NaN,NaN,0
124320,2025-10-23 06:00,2000.0,BR,NaN,NaN,0
124447,2025-10-29 12:00,7000.0,NaN,NaN,NaN,0
124448,2025-10-29 13:00,7000.0,NaN,NaN,NaN,0
124449,2025-10-29 14:00,7000.0,-DZ,NaN,NaN,1
124467,2025-10-30 12:00,2000.0,BR,NaN,NaN,0
124550,2025-11-03 12:00,300.0,FG,NaN,NaN,0
124551,2025-11-03 12:05,3000.0,FG,NaN,NaN,0
124638,2025-11-08 12:00,5000.0,BR,NaN,NaN,0
124791,2025-11-16 12:00,2000.0,BR,NaN,NaN,0
124792,2025-11-16 13:00,3000.0,BR,NaN,NaN,0
124812,2025-11-17 12:00,500.0,FG,NaN,NaN,0
124813,2025-11-17 12:19,3000.0,BR,NaN,NaN,0
124814,2025-11-17 13:00,6000.0,BCFG,NaN,NaN,0
124815,2025-11-17 14:00,4000.0,BR,NaN,NaN,0
125258,2025-12-09 12:49,500.0,FG,NaN,NaN,0
125259,2025-12-09 13:00,100.0,FG,NaN,NaN,0
125260,2025-12-09 13:43,7000.0,NaN,NaN,NaN,0

In [121]:
df['obscuration'] = 0
df.loc[df['weather_2'].astype(str).str.match('BR|FG|BCFG'), 'obscuration'] = 1
df.loc[df['weather_1'].astype(str).str.match('BR|FG|BCFG'), 'obscuration'] = 1
df.loc[df['weather_3'].astype(str).str.match('BR|FG|BCFG'), 'obscuration'] = 1
df.head(50)

,date,visibility_m,weather_1,weather_2,weather_3,precipitation,obscuration
1680,2005-05-16 17:00,1500.0,RA,NaN,NaN,1,0
1681,2005-05-16 18:00,4000.0,RA,NaN,NaN,1,0
1682,2005-05-16 19:00,2500.0,RA,NaN,NaN,1,0
1732,2005-05-20 18:00,5000.0,RA,NaN,NaN,1,0
1734,2005-05-20 20:00,3000.0,RA,NaN,NaN,1,0
1736,2005-05-20 22:00,7000.0,-RA,NaN,NaN,1,0
1751,2005-05-22 12:00,200.0,FG,NaN,NaN,0,1
1752,2005-05-22 13:00,3000.0,BR,NaN,NaN,0,1
1764,2005-05-23 12:00,1000.0,BR,NaN,NaN,0,1
1801,2005-05-26 12:00,3000.0,BR,NaN,NaN,0,1
1814,2005-05-27 12:00,2000.0,BR,NaN,NaN,0,1
1925,2005-06-05 00:00,1500.0,RA,NaN,NaN,1,0
1955,2005-06-07 16:00,5000.0,-RA,NaN,NaN,1,0
1958,2005-06-07 19:00,4000.0,-RA,NaN,NaN,1,0
1959,2005-06-07 20:00,3000.0,-RA,BR,NaN,1,1
1988,2005-06-10 13:00,3000.0,-RA,BR,NaN,1,1
2000,2005-06-11 12:00,2000.0,-RA,BR,NaN,1,1
2001,2005-06-11 13:00,5000.0,RA,NaN,NaN,1,0
2008,2005-06-11 20:00,3000.0,-RA,NaN,NaN,1,0
2035,2005-06-14 12:00,400.0,FG,NaN,NaN,0,1
2036,2005-06-14 13:00,1000.0,BR,NaN,NaN,0,1
2084,2005-06-18 13:00,2000.0,BR,NaN,NaN,0,1
2085,2005-06-18 14:00,5000.0,BR,NaN,NaN,0,1
2093,2005-06-18 22:00,3000.0,-TSRA,NaN,NaN,1,0
2096,2005-06-19 12:00,500.0,FG,NaN,NaN,0,1
2097,2005-06-19 13:00,500.0,FG,NaN,NaN,0,1
2152,2005-06-23 20:00,500.0,+RA,NaN,NaN,1,0
2153,2005-06-23 21:00,2000.0,-RA,BR,NaN,1,1
2157,2005-06-24 12:00,4000.0,BR,NaN,NaN,0,1
2170,2005-06-25 12:00,1500.0,BR,NaN,NaN,0,1
2182,2005-06-26 12:00,100.0,FG,NaN,NaN,0,1
2183,2005-06-26 13:00,500.0,FG,NaN,NaN,0,1
2190,2005-06-26 20:00,7000.0,VCSH,NaN,NaN,0,0
2192,2005-06-26 22:00,3000.0,RA,BR,NaN,1,1
2195,2005-06-27 12:00,200.0,FG,NaN,NaN,0,1
2196,2005-06-27 13:00,2000.0,BR,NaN,NaN,0,1
2216,2005-06-28 21:00,2500.0,-TSRA,NaN,NaN,1,0
2218,2005-06-28 23:00,6000.0,-RA,NaN,NaN,1,0
2223,2005-06-29 15:00,3000.0,RA,NaN,NaN,1,0
2332,2005-07-08 12:00,200.0,FG,NaN,NaN,0,1
2333,2005-07-08 13:00,500.0,FG,NaN,NaN,0,1
2377,2005-07-11 20:00,2000.0,RA,NaN,NaN,1,0
2445,2005-07-17 12:00,500.0,FG,NaN,NaN,0,1
2779,2005-08-13 20:00,5000.0,-RA,NaN,NaN,1,0
2844,2005-08-18 20:00,2000.0,-TSRA,NaN,NaN,1,0
2849,2005-08-19 12:00,600.0,FG,NaN,NaN,0,1
2899,2005-08-22 23:00,1000.0,TSRA,NaN,NaN,1,0
2929,2005-08-26 12:00,100.0,FG,NaN,NaN,0,1
2930,2005-08-26 13:00,400.0,FG,NaN,NaN,0,1
2937,2005-08-26 20:00,2000.0,RA,NaN,NaN,1,0

In [122]:
df.tail(50)

,date,visibility_m,weather_1,weather_2,weather_3,precipitation,obscuration
124067,2025-10-12 12:33,1000.0,RA,NaN,NaN,1,0
124070,2025-10-12 15:00,5000.0,-RA,NaN,NaN,1,0
124071,2025-10-12 15:16,1000.0,RA,NaN,NaN,1,0
124072,2025-10-12 16:00,3000.0,RA,NaN,NaN,1,0
124073,2025-10-12 17:00,5000.0,-RA,NaN,NaN,1,0
124075,2025-10-12 19:00,7000.0,-RA,NaN,NaN,1,0
124123,2025-10-14 22:10,5000.0,+TSRA,BR,NaN,1,1
124124,2025-10-14 22:40,5000.0,TSRA,BR,NaN,1,1
124133,2025-10-15 12:00,100.0,FG,NaN,NaN,0,1
124134,2025-10-15 13:00,200.0,FG,NaN,NaN,0,1
124135,2025-10-15 13:20,5000.0,BR,NaN,NaN,0,1
124136,2025-10-15 14:00,7000.0,BCFG,NaN,NaN,0,1
124143,2025-10-15 19:17,3000.0,TSRA,NaN,NaN,1,0
124166,2025-10-16 18:07,3000.0,+TSRA,BR,NaN,1,1
124167,2025-10-16 18:18,5000.0,TSRA,BR,NaN,1,1
124173,2025-10-16 22:30,6000.0,RA,NaN,NaN,1,0
124174,2025-10-16 23:00,5000.0,RA,NaN,NaN,1,0
124175,2025-10-16 23:24,2000.0,+RA,NaN,NaN,1,0
124176,2025-10-17 00:00,2000.0,RA,NaN,NaN,1,0
124177,2025-10-17 00:00,2000.0,RA,NaN,NaN,1,0
124179,2025-10-17 01:00,6000.0,RA,NaN,NaN,1,0
124185,2025-10-17 12:00,1000.0,FG,NaN,NaN,0,1
124186,2025-10-17 12:09,3000.0,BCFG,NaN,NaN,0,1
124188,2025-10-17 13:21,5000.0,BR,NaN,NaN,0,1
124189,2025-10-17 14:00,6000.0,VCFG,NaN,NaN,0,0
124197,2025-10-17 20:49,5000.0,TSRA,NaN,NaN,1,0
124198,2025-10-17 21:00,2000.0,RA,NaN,NaN,1,0
124208,2025-10-18 05:00,4000.0,BR,NaN,NaN,0,1
124209,2025-10-18 06:00,3000.0,BR,NaN,NaN,0,1
124221,2025-10-18 21:08,800.0,RA,NaN,NaN,1,0
124236,2025-10-19 12:38,500.0,FG,NaN,NaN,0,1
124311,2025-10-22 22:00,5000.0,TSRA,NaN,NaN,1,0
124319,2025-10-23 05:00,3000.0,BR,NaN,NaN,0,1
124320,2025-10-23 06:00,2000.0,BR,NaN,NaN,0,1
124447,2025-10-29 12:00,7000.0,NaN,NaN,NaN,0,0
124448,2025-10-29 13:00,7000.0,NaN,NaN,NaN,0,0
124449,2025-10-29 14:00,7000.0,-DZ,NaN,NaN,1,0
124467,2025-10-30 12:00,2000.0,BR,NaN,NaN,0,1
124550,2025-11-03 12:00,300.0,FG,NaN,NaN,0,1
124551,2025-11-03 12:05,3000.0,FG,NaN,NaN,0,1
124638,2025-11-08 12:00,5000.0,BR,NaN,NaN,0,1
124791,2025-11-16 12:00,2000.0,BR,NaN,NaN,0,1
124792,2025-11-16 13:00,3000.0,BR,NaN,NaN,0,1
124812,2025-11-17 12:00,500.0,FG,NaN,NaN,0,1
124813,2025-11-17 12:19,3000.0,BR,NaN,NaN,0,1
124814,2025-11-17 13:00,6000.0,BCFG,NaN,NaN,0,1
124815,2025-11-17 14:00,4000.0,BR,NaN,NaN,0,1
125258,2025-12-09 12:49,500.0,FG,NaN,NaN,0,1
125259,2025-12-09 13:00,100.0,FG,NaN,NaN,0,1
125260,2025-12-09 13:43,7000.0,NaN,NaN,NaN,0,0

In [123]:
df['thunderstorm'] = 0
df.loc[df['weather_1'].astype(str).str.match(r'(\+|-)?(TS|TSRA)'), 'thunderstorm'] = 1
df.loc[df['weather_2'].astype(str).str.match(r'(\+|-)?(TS|TSRA)'), 'thunderstorm'] = 1
df.loc[df['weather_3'].astype(str).str.match(r'(\+|-)?(TS|TSRA)'), 'thunderstorm'] = 1
df.head(50)

,date,visibility_m,weather_1,weather_2,weather_3,precipitation,obscuration,thunderstorm
1680,2005-05-16 17:00,1500.0,RA,NaN,NaN,1,0,0
1681,2005-05-16 18:00,4000.0,RA,NaN,NaN,1,0,0
1682,2005-05-16 19:00,2500.0,RA,NaN,NaN,1,0,0
1732,2005-05-20 18:00,5000.0,RA,NaN,NaN,1,0,0
1734,2005-05-20 20:00,3000.0,RA,NaN,NaN,1,0,0
1736,2005-05-20 22:00,7000.0,-RA,NaN,NaN,1,0,0
1751,2005-05-22 12:00,200.0,FG,NaN,NaN,0,1,0
1752,2005-05-22 13:00,3000.0,BR,NaN,NaN,0,1,0
1764,2005-05-23 12:00,1000.0,BR,NaN,NaN,0,1,0
1801,2005-05-26 12:00,3000.0,BR,NaN,NaN,0,1,0
1814,2005-05-27 12:00,2000.0,BR,NaN,NaN,0,1,0
1925,2005-06-05 00:00,1500.0,RA,NaN,NaN,1,0,0
1955,2005-06-07 16:00,5000.0,-RA,NaN,NaN,1,0,0
1958,2005-06-07 19:00,4000.0,-RA,NaN,NaN,1,0,0
1959,2005-06-07 20:00,3000.0,-RA,BR,NaN,1,1,0
1988,2005-06-10 13:00,3000.0,-RA,BR,NaN,1,1,0
2000,2005-06-11 12:00,2000.0,-RA,BR,NaN,1,1,0
2001,2005-06-11 13:00,5000.0,RA,NaN,NaN,1,0,0
2008,2005-06-11 20:00,3000.0,-RA,NaN,NaN,1,0,0
2035,2005-06-14 12:00,400.0,FG,NaN,NaN,0,1,0
2036,2005-06-14 13:00,1000.0,BR,NaN,NaN,0,1,0
2084,2005-06-18 13:00,2000.0,BR,NaN,NaN,0,1,0
2085,2005-06-18 14:00,5000.0,BR,NaN,NaN,0,1,0
2093,2005-06-18 22:00,3000.0,-TSRA,NaN,NaN,1,0,1
2096,2005-06-19 12:00,500.0,FG,NaN,NaN,0,1,0
2097,2005-06-19 13:00,500.0,FG,NaN,NaN,0,1,0
2152,2005-06-23 20:00,500.0,+RA,NaN,NaN,1,0,0
2153,2005-06-23 21:00,2000.0,-RA,BR,NaN,1,1,0
2157,2005-06-24 12:00,4000.0,BR,NaN,NaN,0,1,0
2170,2005-06-25 12:00,1500.0,BR,NaN,NaN,0,1,0
2182,2005-06-26 12:00,100.0,FG,NaN,NaN,0,1,0
2183,2005-06-26 13:00,500.0,FG,NaN,NaN,0,1,0
2190,2005-06-26 20:00,7000.0,VCSH,NaN,NaN,0,0,0
2192,2005-06-26 22:00,3000.0,RA,BR,NaN,1,1,0
2195,2005-06-27 12:00,200.0,FG,NaN,NaN,0,1,0
2196,2005-06-27 13:00,2000.0,BR,NaN,NaN,0,1,0
2216,2005-06-28 21:00,2500.0,-TSRA,NaN,NaN,1,0,1
2218,2005-06-28 23:00,6000.0,-RA,NaN,NaN,1,0,0
2223,2005-06-29 15:00,3000.0,RA,NaN,NaN,1,0,0
2332,2005-07-08 12:00,200.0,FG,NaN,NaN,0,1,0
2333,2005-07-08 13:00,500.0,FG,NaN,NaN,0,1,0
2377,2005-07-11 20:00,2000.0,RA,NaN,NaN,1,0,0
2445,2005-07-17 12:00,500.0,FG,NaN,NaN,0,1,0
2779,2005-08-13 20:00,5000.0,-RA,NaN,NaN,1,0,0
2844,2005-08-18 20:00,2000.0,-TSRA,NaN,NaN,1,0,1
2849,2005-08-19 12:00,600.0,FG,NaN,NaN,0,1,0
2899,2005-08-22 23:00,1000.0,TSRA,NaN,NaN,1,0,1
2929,2005-08-26 12:00,100.0,FG,NaN,NaN,0,1,0
2930,2005-08-26 13:00,400.0,FG,NaN,NaN,0,1,0
2937,2005-08-26 20:00,2000.0,RA,NaN,NaN,1,0,0

In [124]:
df.tail(50)

,date,visibility_m,weather_1,weather_2,weather_3,precipitation,obscuration,thunderstorm
124067,2025-10-12 12:33,1000.0,RA,NaN,NaN,1,0,0
124070,2025-10-12 15:00,5000.0,-RA,NaN,NaN,1,0,0
124071,2025-10-12 15:16,1000.0,RA,NaN,NaN,1,0,0
124072,2025-10-12 16:00,3000.0,RA,NaN,NaN,1,0,0
124073,2025-10-12 17:00,5000.0,-RA,NaN,NaN,1,0,0
124075,2025-10-12 19:00,7000.0,-RA,NaN,NaN,1,0,0
124123,2025-10-14 22:10,5000.0,+TSRA,BR,NaN,1,1,1
124124,2025-10-14 22:40,5000.0,TSRA,BR,NaN,1,1,1
124133,2025-10-15 12:00,100.0,FG,NaN,NaN,0,1,0
124134,2025-10-15 13:00,200.0,FG,NaN,NaN,0,1,0
124135,2025-10-15 13:20,5000.0,BR,NaN,NaN,0,1,0
124136,2025-10-15 14:00,7000.0,BCFG,NaN,NaN,0,1,0
124143,2025-10-15 19:17,3000.0,TSRA,NaN,NaN,1,0,1
124166,2025-10-16 18:07,3000.0,+TSRA,BR,NaN,1,1,1
124167,2025-10-16 18:18,5000.0,TSRA,BR,NaN,1,1,1
124173,2025-10-16 22:30,6000.0,RA,NaN,NaN,1,0,0
124174,2025-10-16 23:00,5000.0,RA,NaN,NaN,1,0,0
124175,2025-10-16 23:24,2000.0,+RA,NaN,NaN,1,0,0
124176,2025-10-17 00:00,2000.0,RA,NaN,NaN,1,0,0
124177,2025-10-17 00:00,2000.0,RA,NaN,NaN,1,0,0
124179,2025-10-17 01:00,6000.0,RA,NaN,NaN,1,0,0
124185,2025-10-17 12:00,1000.0,FG,NaN,NaN,0,1,0
124186,2025-10-17 12:09,3000.0,BCFG,NaN,NaN,0,1,0
124188,2025-10-17 13:21,5000.0,BR,NaN,NaN,0,1,0
124189,2025-10-17 14:00,6000.0,VCFG,NaN,NaN,0,0,0
124197,2025-10-17 20:49,5000.0,TSRA,NaN,NaN,1,0,1
124198,2025-10-17 21:00,2000.0,RA,NaN,NaN,1,0,0
124208,2025-10-18 05:00,4000.0,BR,NaN,NaN,0,1,0
124209,2025-10-18 06:00,3000.0,BR,NaN,NaN,0,1,0
124221,2025-10-18 21:08,800.0,RA,NaN,NaN,1,0,0
124236,2025-10-19 12:38,500.0,FG,NaN,NaN,0,1,0
124311,2025-10-22 22:00,5000.0,TSRA,NaN,NaN,1,0,1
124319,2025-10-23 05:00,3000.0,BR,NaN,NaN,0,1,0
124320,2025-10-23 06:00,2000.0,BR,NaN,NaN,0,1,0
124447,2025-10-29 12:00,7000.0,NaN,NaN,NaN,0,0,0
124448,2025-10-29 13:00,7000.0,NaN,NaN,NaN,0,0,0
124449,2025-10-29 14:00,7000.0,-DZ,NaN,NaN,1,0,0
124467,2025-10-30 12:00,2000.0,BR,NaN,NaN,0,1,0
124550,2025-11-03 12:00,300.0,FG,NaN,NaN,0,1,0
124551,2025-11-03 12:05,3000.0,FG,NaN,NaN,0,1,0
124638,2025-11-08 12:00,5000.0,BR,NaN,NaN,0,1,0
124791,2025-11-16 12:00,2000.0,BR,NaN,NaN,0,1,0
124792,2025-11-16 13:00,3000.0,BR,NaN,NaN,0,1,0
124812,2025-11-17 12:00,500.0,FG,NaN,NaN,0,1,0
124813,2025-11-17 12:19,3000.0,BR,NaN,NaN,0,1,0
124814,2025-11-17 13:00,6000.0,BCFG,NaN,NaN,0,1,0
124815,2025-11-17 14:00,4000.0,BR,NaN,NaN,0,1,0
125258,2025-12-09 12:49,500.0,FG,NaN,NaN,0,1,0
125259,2025-12-09 13:00,100.0,FG,NaN,NaN,0,1,0
125260,2025-12-09 13:43,7000.0,NaN,NaN,NaN,0,0,0

In [125]:
df["limited_visibility"] = 0
df.loc[df["visibility_m"].astype(float) < 5000.0, "limited_visibility"] = 1
df.head(50)

,date,visibility_m,weather_1,weather_2,weather_3,precipitation,obscuration,thunderstorm,limited_visibility
1680,2005-05-16 17:00,1500.0,RA,NaN,NaN,1,0,0,1
1681,2005-05-16 18:00,4000.0,RA,NaN,NaN,1,0,0,1
1682,2005-05-16 19:00,2500.0,RA,NaN,NaN,1,0,0,1
1732,2005-05-20 18:00,5000.0,RA,NaN,NaN,1,0,0,0
1734,2005-05-20 20:00,3000.0,RA,NaN,NaN,1,0,0,1
1736,2005-05-20 22:00,7000.0,-RA,NaN,NaN,1,0,0,0
1751,2005-05-22 12:00,200.0,FG,NaN,NaN,0,1,0,1
1752,2005-05-22 13:00,3000.0,BR,NaN,NaN,0,1,0,1
1764,2005-05-23 12:00,1000.0,BR,NaN,NaN,0,1,0,1
1801,2005-05-26 12:00,3000.0,BR,NaN,NaN,0,1,0,1
1814,2005-05-27 12:00,2000.0,BR,NaN,NaN,0,1,0,1
1925,2005-06-05 00:00,1500.0,RA,NaN,NaN,1,0,0,1
1955,2005-06-07 16:00,5000.0,-RA,NaN,NaN,1,0,0,0
1958,2005-06-07 19:00,4000.0,-RA,NaN,NaN,1,0,0,1
1959,2005-06-07 20:00,3000.0,-RA,BR,NaN,1,1,0,1
1988,2005-06-10 13:00,3000.0,-RA,BR,NaN,1,1,0,1
2000,2005-06-11 12:00,2000.0,-RA,BR,NaN,1,1,0,1
2001,2005-06-11 13:00,5000.0,RA,NaN,NaN,1,0,0,0
2008,2005-06-11 20:00,3000.0,-RA,NaN,NaN,1,0,0,1
2035,2005-06-14 12:00,400.0,FG,NaN,NaN,0,1,0,1
2036,2005-06-14 13:00,1000.0,BR,NaN,NaN,0,1,0,1
2084,2005-06-18 13:00,2000.0,BR,NaN,NaN,0,1,0,1
2085,2005-06-18 14:00,5000.0,BR,NaN,NaN,0,1,0,0
2093,2005-06-18 22:00,3000.0,-TSRA,NaN,NaN,1,0,1,1
2096,2005-06-19 12:00,500.0,FG,NaN,NaN,0,1,0,1
2097,2005-06-19 13:00,500.0,FG,NaN,NaN,0,1,0,1
2152,2005-06-23 20:00,500.0,+RA,NaN,NaN,1,0,0,1
2153,2005-06-23 21:00,2000.0,-RA,BR,NaN,1,1,0,1
2157,2005-06-24 12:00,4000.0,BR,NaN,NaN,0,1,0,1
2170,2005-06-25 12:00,1500.0,BR,NaN,NaN,0,1,0,1
2182,2005-06-26 12:00,100.0,FG,NaN,NaN,0,1,0,1
2183,2005-06-26 13:00,500.0,FG,NaN,NaN,0,1,0,1
2190,2005-06-26 20:00,7000.0,VCSH,NaN,NaN,0,0,0,0
2192,2005-06-26 22:00,3000.0,RA,BR,NaN,1,1,0,1
2195,2005-06-27 12:00,200.0,FG,NaN,NaN,0,1,0,1
2196,2005-06-27 13:00,2000.0,BR,NaN,NaN,0,1,0,1
2216,2005-06-28 21:00,2500.0,-TSRA,NaN,NaN,1,0,1,1
2218,2005-06-28 23:00,6000.0,-RA,NaN,NaN,1,0,0,0
2223,2005-06-29 15:00,3000.0,RA,NaN,NaN,1,0,0,1
2332,2005-07-08 12:00,200.0,FG,NaN,NaN,0,1,0,1
2333,2005-07-08 13:00,500.0,FG,NaN,NaN,0,1,0,1
2377,2005-07-11 20:00,2000.0,RA,NaN,NaN,1,0,0,1
2445,2005-07-17 12:00,500.0,FG,NaN,NaN,0,1,0,1
2779,2005-08-13 20:00,5000.0,-RA,NaN,NaN,1,0,0,0
2844,2005-08-18 20:00,2000.0,-TSRA,NaN,NaN,1,0,1,1
2849,2005-08-19 12:00,600.0,FG,NaN,NaN,0,1,0,1
2899,2005-08-22 23:00,1000.0,TSRA,NaN,NaN,1,0,1,1
2929,2005-08-26 12:00,100.0,FG,NaN,NaN,0,1,0,1
2930,2005-08-26 13:00,400.0,FG,NaN,NaN,0,1,0,1
2937,2005-08-26 20:00,2000.0,RA,NaN,NaN,1,0,0,1

In [126]:
df.tail(50)

,date,visibility_m,weather_1,weather_2,weather_3,precipitation,obscuration,thunderstorm,limited_visibility
124067,2025-10-12 12:33,1000.0,RA,NaN,NaN,1,0,0,1
124070,2025-10-12 15:00,5000.0,-RA,NaN,NaN,1,0,0,0
124071,2025-10-12 15:16,1000.0,RA,NaN,NaN,1,0,0,1
124072,2025-10-12 16:00,3000.0,RA,NaN,NaN,1,0,0,1
124073,2025-10-12 17:00,5000.0,-RA,NaN,NaN,1,0,0,0
124075,2025-10-12 19:00,7000.0,-RA,NaN,NaN,1,0,0,0
124123,2025-10-14 22:10,5000.0,+TSRA,BR,NaN,1,1,1,0
124124,2025-10-14 22:40,5000.0,TSRA,BR,NaN,1,1,1,0
124133,2025-10-15 12:00,100.0,FG,NaN,NaN,0,1,0,1
124134,2025-10-15 13:00,200.0,FG,NaN,NaN,0,1,0,1
124135,2025-10-15 13:20,5000.0,BR,NaN,NaN,0,1,0,0
124136,2025-10-15 14:00,7000.0,BCFG,NaN,NaN,0,1,0,0
124143,2025-10-15 19:17,3000.0,TSRA,NaN,NaN,1,0,1,1
124166,2025-10-16 18:07,3000.0,+TSRA,BR,NaN,1,1,1,1
124167,2025-10-16 18:18,5000.0,TSRA,BR,NaN,1,1,1,0
124173,2025-10-16 22:30,6000.0,RA,NaN,NaN,1,0,0,0
124174,2025-10-16 23:00,5000.0,RA,NaN,NaN,1,0,0,0
124175,2025-10-16 23:24,2000.0,+RA,NaN,NaN,1,0,0,1
124176,2025-10-17 00:00,2000.0,RA,NaN,NaN,1,0,0,1
124177,2025-10-17 00:00,2000.0,RA,NaN,NaN,1,0,0,1
124179,2025-10-17 01:00,6000.0,RA,NaN,NaN,1,0,0,0
124185,2025-10-17 12:00,1000.0,FG,NaN,NaN,0,1,0,1
124186,2025-10-17 12:09,3000.0,BCFG,NaN,NaN,0,1,0,1
124188,2025-10-17 13:21,5000.0,BR,NaN,NaN,0,1,0,0
124189,2025-10-17 14:00,6000.0,VCFG,NaN,NaN,0,0,0,0
124197,2025-10-17 20:49,5000.0,TSRA,NaN,NaN,1,0,1,0
124198,2025-10-17 21:00,2000.0,RA,NaN,NaN,1,0,0,1
124208,2025-10-18 05:00,4000.0,BR,NaN,NaN,0,1,0,1
124209,2025-10-18 06:00,3000.0,BR,NaN,NaN,0,1,0,1
124221,2025-10-18 21:08,800.0,RA,NaN,NaN,1,0,0,1
124236,2025-10-19 12:38,500.0,FG,NaN,NaN,0,1,0,1
124311,2025-10-22 22:00,5000.0,TSRA,NaN,NaN,1,0,1,0
124319,2025-10-23 05:00,3000.0,BR,NaN,NaN,0,1,0,1
124320,2025-10-23 06:00,2000.0,BR,NaN,NaN,0,1,0,1
124447,2025-10-29 12:00,7000.0,NaN,NaN,NaN,0,0,0,0
124448,2025-10-29 13:00,7000.0,NaN,NaN,NaN,0,0,0,0
124449,2025-10-29 14:00,7000.0,-DZ,NaN,NaN,1,0,0,0
124467,2025-10-30 12:00,2000.0,BR,NaN,NaN,0,1,0,1
124550,2025-11-03 12:00,300.0,FG,NaN,NaN,0,1,0,1
124551,2025-11-03 12:05,3000.0,FG,NaN,NaN,0,1,0,1
124638,2025-11-08 12:00,5000.0,BR,NaN,NaN,0,1,0,0
124791,2025-11-16 12:00,2000.0,BR,NaN,NaN,0,1,0,1
124792,2025-11-16 13:00,3000.0,BR,NaN,NaN,0,1,0,1
124812,2025-11-17 12:00,500.0,FG,NaN,NaN,0,1,0,1
124813,2025-11-17 12:19,3000.0,BR,NaN,NaN,0,1,0,1
124814,2025-11-17 13:00,6000.0,BCFG,NaN,NaN,0,1,0,0
124815,2025-11-17 14:00,4000.0,BR,NaN,NaN,0,1,0,1
125258,2025-12-09 12:49,500.0,FG,NaN,NaN,0,1,0,1
125259,2025-12-09 13:00,100.0,FG,NaN,NaN,0,1,0,1
125260,2025-12-09 13:43,7000.0,NaN,NaN,NaN,0,0,0,0

In [135]:
data['precipitation'] = 0
data.loc[data['weather_1'].astype(str).str.contains('RA|DZ', regex=True), 'precipitation'] = 1
data.loc[data['weather_2'].astype(str).str.contains('RA|DZ', regex=True), 'precipitation'] = 1
data.loc[data['weather_3'].astype(str).str.contains('RA|DZ', regex=True), 'precipitation'] = 1
data['obscuration'] = 0
data.loc[data['weather_2'].astype(str).str.match('BR|FG|BCFG'), 'obscuration'] = 1
data.loc[data['weather_1'].astype(str).str.match('BR|FG|BCFG'), 'obscuration'] = 1
data.loc[data['weather_3'].astype(str).str.match('BR|FG|BCFG'), 'obscuration'] = 1
data['thunderstorm'] = 0
data.loc[data['weather_1'].astype(str).str.match(r'(\+|-)?(TS|TSRA)'), 'thunderstorm'] = 1
data.loc[data['weather_2'].astype(str).str.match(r'(\+|-)?(TS|TSRA)'), 'thunderstorm'] = 1
data.loc[data['weather_3'].astype(str).str.match(r'(\+|-)?(TS|TSRA)'), 'thunderstorm'] = 1
data["limited_visibility"] = 0
data.loc[data["visibility_m"].astype(float) < 5000.0, "limited_visibility"] = 1
data.head(50)

,date,wind_dir_deg,wind_speed_kt,wind_gust_kt,visibility_m,is_cavok,weather_1,weather_2,weather_3,is_ceiling,temp_c,dewpoint_c,pressure_inhg,precipitation,obscuration,thunderstorm,limited_visibility
0,2005-01-01 01:00,80.0,15.0,NaN,10000.0,0,NaN,NaN,NaN,0,27.0,19.0,29.84,0,0,0,0
1,2005-01-01 13:00,30.0,4.0,NaN,10000.0,0,NaN,NaN,NaN,0,23.0,20.0,29.90,0,0,0,0
2,2005-01-01 14:00,50.0,4.0,NaN,10000.0,0,NaN,NaN,NaN,0,27.0,20.0,29.92,0,0,0,0
3,2005-01-01 15:00,60.0,16.0,NaN,10000.0,0,NaN,NaN,NaN,0,30.0,20.0,29.94,0,0,0,0
4,2005-01-01 16:00,70.0,14.0,NaN,10000.0,0,NaN,NaN,NaN,0,31.0,20.0,29.93,0,0,0,0
5,2005-01-01 17:00,80.0,16.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.92,0,0,0,0
6,2005-01-01 18:00,70.0,14.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.90,0,0,0,0
7,2005-01-01 19:00,60.0,13.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.86,0,0,0,0
8,2005-01-01 20:00,50.0,14.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.83,0,0,0,0
9,2005-01-01 21:00,60.0,12.0,NaN,10000.0,0,NaN,NaN,NaN,0,31.0,29.0,29.82,0,0,0,0
10,2005-01-01 22:00,50.0,18.0,NaN,10000.0,0,NaN,NaN,NaN,0,31.0,20.0,29.82,0,0,0,0
11,2005-01-01 23:00,60.0,13.0,NaN,10000.0,0,NaN,NaN,NaN,0,30.0,19.0,29.83,0,0,0,0
12,2005-01-02 00:00,70.0,13.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,19.0,29.84,0,0,0,0
13,2005-01-02 01:00,80.0,10.0,NaN,10000.0,1,NaN,NaN,NaN,0,27.0,20.0,29.87,0,0,0,0
14,2005-01-02 13:00,0.0,0.0,NaN,10000.0,0,NaN,NaN,NaN,0,26.0,20.0,29.88,0,0,0,0
15,2005-01-02 14:00,90.0,16.0,NaN,10000.0,0,NaN,NaN,NaN,0,28.0,20.0,29.90,0,0,0,0
16,2005-01-02 15:00,80.0,14.0,NaN,10000.0,0,NaN,NaN,NaN,0,30.0,20.0,29.91,0,0,0,0
17,2005-01-02 16:00,80.0,20.0,NaN,10000.0,0,NaN,NaN,NaN,0,31.0,20.0,29.91,0,0,0,0
18,2005-01-02 17:00,90.0,23.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.89,0,0,0,0
19,2005-01-02 18:00,70.0,21.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.87,0,0,0,0
20,2005-01-02 19:00,80.0,16.0,NaN,10000.0,0,NaN,NaN,NaN,0,33.0,20.0,29.84,0,0,0,0
21,2005-01-02 20:00,100.0,17.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,21.0,29.81,0,0,0,0
22,2005-01-02 21:00,80.0,15.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,21.0,29.80,0,0,0,0
23,2005-01-02 22:00,80.0,16.0,NaN,10000.0,0,NaN,NaN,NaN,0,29.0,21.0,29.81,0,0,0,0
24,2005-01-02 23:00,80.0,12.0,NaN,10000.0,0,NaN,NaN,NaN,0,29.0,21.0,29.82,0,0,0,0
25,2005-01-03 00:00,60.0,19.0,NaN,10000.0,0,NaN,NaN,NaN,0,27.0,21.0,29.85,0,0,0,0
26,2005-01-03 01:00,70.0,25.0,NaN,10000.0,0,NaN,NaN,NaN,0,27.0,20.0,29.86,0,0,0,0
27,2005-01-03 12:00,60.0,17.0,NaN,10000.0,1,NaN,NaN,NaN,0,27.0,19.0,29.84,0,0,0,0
28,2005-01-03 13:00,80.0,17.0,NaN,10000.0,1,NaN,NaN,NaN,0,27.0,20.0,29.85,0,0,0,0
29,2005-01-03 14:00,80.0,18.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,20.0,29.88,0,0,0,0
30,2005-01-03 15:00,80.0,22.0,NaN,10000.0,0,NaN,NaN,NaN,0,29.0,19.0,29.88,0,0,0,0
31,2005-01-03 16:00,70.0,20.0,NaN,10000.0,0,NaN,NaN,NaN,0,30.0,20.0,29.89,0,0,0,0
32,2005-01-03 17:00,70.0,19.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,21.0,29.87,0,0,0,0
33,2005-01-03 18:00,60.0,24.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.84,0,0,0,0
34,2005-01-03 19:00,70.0,22.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.82,0,0,0,0
35,2005-01-03 20:00,70.0,21.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,19.0,29.80,0,0,0,0
36,2005-01-03 21:00,60.0,23.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,19.0,29.78,0,0,0,0
37,2005-01-03 22:00,70.0,18.0,NaN,10000.0,0,NaN,NaN,NaN,0,31.0,20.0,29.78,0,0,0,0
38,2005-01-03 23:00,70.0,19.0,NaN,10000.0,0,NaN,NaN,NaN,0,29.0,20.0,29.79,0,0,0,0
39,2005-01-04 00:00,70.0,17.0,NaN,10000.0,0,NaN,NaN,NaN,0,28.0,20.0,29.80,0,0,0,0
40,2005-01-04 12:00,270.0,4.0,NaN,10000.0,0,NaN,NaN,NaN,0,23.0,19.0,29.84,0,0,0,0
41,2005-01-04 13:00,220.0,10.0,NaN,10000.0,0,NaN,NaN,NaN,0,24.0,19.0,29.86,0,0,0,0
42,2005-01-04 14:00,220.0,13.0,NaN,10000.0,1,NaN,NaN,NaN,0,27.0,19.0,29.88,0,0,0,0
43,2005-01-04 15:00,270.0,6.0,NaN,10000.0,1,NaN,NaN,NaN,0,29.0,19.0,29.88,0,0,0,0
44,2005-01-04 16:00,90.0,9.0,NaN,10000.0,1,NaN,NaN,NaN,0,31.0,17.0,29.87,0,0,0,0
45,2005-01-04 17:00,70.0,13.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,18.0,29.85,0,0,0,0
46,2005-01-04 18:00,270.0,5.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,18.0,29.82,0,0,0,0
47,2005-01-04 19:00,80.0,21.0,NaN,10000.0,0,NaN,NaN,NaN,0,33.0,19.0,29.87,0,0,0,0
48,2005-01-04 20:00,70.0,19.0,NaN,10000.0,0,NaN,NaN,NaN,0,31.0,18.0,29.76,0,0,0,0
49,2005-01-04 21:00,70.0,22.0,NaN,10000.0,0,NaN,NaN,NaN,0,29.0,19.0,29.75,0,0,0,0

In [136]:
data.tail(50)

,date,wind_dir_deg,wind_speed_kt,wind_gust_kt,visibility_m,is_cavok,weather_1,weather_2,weather_3,is_ceiling,temp_c,dewpoint_c,pressure_inhg,precipitation,obscuration,thunderstorm,limited_visibility
125657,2025-12-29 14:00,100.0,8.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,21.0,29.87,0,0,0,0
125658,2025-12-29 15:00,90.0,8.0,NaN,10000.0,1,NaN,NaN,NaN,0,30.0,20.0,29.88,0,0,0,0
125659,2025-12-29 16:00,80.0,11.0,NaN,10000.0,1,NaN,NaN,NaN,0,32.0,20.0,29.86,0,0,0,0
125660,2025-12-29 17:00,90.0,11.0,NaN,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.86,0,0,0,0
125661,2025-12-29 18:00,80.0,10.0,20.0,10000.0,0,NaN,NaN,NaN,0,32.0,20.0,29.82,0,0,0,0
125662,2025-12-29 19:00,80.0,10.0,NaN,10000.0,0,NaN,NaN,NaN,0,33.0,20.0,29.79,0,0,0,0
125663,2025-12-29 20:00,90.0,10.0,NaN,10000.0,0,NaN,NaN,NaN,0,33.0,21.0,29.76,0,0,0,0
125664,2025-12-29 21:00,80.0,13.0,NaN,10000.0,0,NaN,NaN,NaN,0,33.0,21.0,29.75,0,0,0,0
125665,2025-12-29 22:00,70.0,12.0,NaN,10000.0,1,NaN,NaN,NaN,0,32.0,21.0,29.76,0,0,0,0
125666,2025-12-29 23:00,70.0,15.0,NaN,10000.0,1,NaN,NaN,NaN,0,30.0,20.0,29.78,0,0,0,0
125667,2025-12-30 00:00,70.0,18.0,NaN,10000.0,1,NaN,NaN,NaN,0,29.0,21.0,29.79,0,0,0,0
125668,2025-12-30 00:00,70.0,18.0,NaN,10000.0,1,NaN,NaN,NaN,0,29.0,21.0,29.79,0,0,0,0
125669,2025-12-30 01:00,90.0,12.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,21.0,29.82,0,0,0,0
125670,2025-12-30 02:00,90.0,15.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,21.0,29.85,0,0,0,0
125671,2025-12-30 03:00,70.0,16.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,21.0,29.86,0,0,0,0
125672,2025-12-30 04:00,110.0,12.0,22.0,10000.0,1,NaN,NaN,NaN,0,27.0,20.0,29.86,0,0,0,0
125673,2025-12-30 05:00,90.0,16.0,NaN,10000.0,1,NaN,NaN,NaN,0,27.0,20.0,29.85,0,0,0,0
125674,2025-12-30 06:00,90.0,13.0,NaN,10000.0,1,NaN,NaN,NaN,0,27.0,20.0,29.84,0,0,0,0
125675,2025-12-30 12:00,NaN,3.0,NaN,10000.0,1,NaN,NaN,NaN,0,21.0,20.0,29.82,0,0,0,0
125676,2025-12-30 13:00,NaN,3.0,NaN,10000.0,1,NaN,NaN,NaN,0,24.0,21.0,29.85,0,0,0,0
125677,2025-12-30 14:00,NaN,3.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,21.0,29.86,0,0,0,0
125678,2025-12-30 15:00,40.0,10.0,NaN,10000.0,1,NaN,NaN,NaN,0,31.0,20.0,29.87,0,0,0,0
125679,2025-12-30 16:00,50.0,9.0,NaN,10000.0,1,NaN,NaN,NaN,0,32.0,20.0,29.85,0,0,0,0
125680,2025-12-30 17:00,70.0,9.0,NaN,10000.0,1,NaN,NaN,NaN,0,33.0,20.0,29.83,0,0,0,0
125681,2025-12-30 18:00,80.0,18.0,NaN,10000.0,1,NaN,NaN,NaN,0,34.0,20.0,29.81,0,0,0,0
125682,2025-12-30 19:00,80.0,18.0,NaN,10000.0,1,NaN,NaN,NaN,0,34.0,19.0,29.79,0,0,0,0
125683,2025-12-30 20:00,70.0,18.0,NaN,10000.0,1,NaN,NaN,NaN,0,34.0,19.0,29.76,0,0,0,0
125684,2025-12-30 21:00,70.0,15.0,NaN,10000.0,1,NaN,NaN,NaN,0,34.0,20.0,29.76,0,0,0,0
125685,2025-12-30 22:00,90.0,16.0,NaN,10000.0,1,NaN,NaN,NaN,0,31.0,21.0,29.77,0,0,0,0
125686,2025-12-30 23:00,90.0,16.0,NaN,10000.0,1,NaN,NaN,NaN,0,29.0,20.0,29.79,0,0,0,0
125687,2025-12-31 00:00,90.0,13.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,19.0,29.81,0,0,0,0
125688,2025-12-31 00:00,90.0,13.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,19.0,29.81,0,0,0,0
125689,2025-12-31 01:00,90.0,15.0,NaN,10000.0,1,NaN,NaN,NaN,0,28.0,19.0,29.82,0,0,0,0
125690,2025-12-31 02:00,90.0,12.0,NaN,10000.0,0,NaN,NaN,NaN,0,28.0,19.0,29.84,0,0,0,0
125691,2025-12-31 03:00,60.0,9.0,NaN,10000.0,0,NaN,NaN,NaN,0,27.0,18.0,29.86,0,0,0,0
125692,2025-12-31 04:00,130.0,5.0,NaN,10000.0,1,NaN,NaN,NaN,0,25.0,19.0,29.87,0,0,0,0
125693,2025-12-31 05:00,NaN,1.0,NaN,10000.0,1,NaN,NaN,NaN,0,25.0,18.0,29.86,0,0,0,0
125694,2025-12-31 06:00,60.0,5.0,NaN,10000.0,1,NaN,NaN,NaN,0,23.0,19.0,29.86,0,0,0,0
125695,2025-12-31 12:00,NaN,3.0,NaN,10000.0,1,NaN,NaN,NaN,0,21.0,19.0,29.88,0,0,0,0
125696,2025-12-31 13:00,250.0,5.0,NaN,10000.0,1,NaN,NaN,NaN,0,24.0,20.0,29.91,0,0,0,0
125697,2025-12-31 14:00,250.0,3.0,NaN,10000.0,1,NaN,NaN,NaN,0,27.0,20.0,29.93,0,0,0,0
125698,2025-12-31 15:00,280.0,5.0,NaN,10000.0,1,NaN,NaN,NaN,0,29.0,20.0,29.93,0,0,0,0
125699,2025-12-31 16:00,NaN,5.0,NaN,10000.0,1,NaN,NaN,NaN,0,31.0,19.0,29.92,0,0,0,0
125700,2025-12-31 17:00,20.0,6.0,NaN,10000.0,1,NaN,NaN,NaN,0,33.0,19.0,29.89,0,0,0,0
125701,2025-12-31 18:00,100.0,13.0,NaN,10000.0,1,NaN,NaN,NaN,0,32.0,19.0,29.87,0,0,0,0
125702,2025-12-31 19:00,90.0,18.0,NaN,10000.0,1,NaN,NaN,NaN,0,33.0,19.0,29.84,0,0,0,0
125703,2025-12-31 20:00,90.0,18.0,28.0,10000.0,1,NaN,NaN,NaN,0,33.0,18.0,29.82,0,0,0,0
125704,2025-12-31 21:00,90.0,19.0,29.0,10000.0,1,NaN,NaN,NaN,0,32.0,18.0,29.80,0,0,0,0
125705,2025-12-31 22:00,70.0,18.0,NaN,10000.0,1,NaN,NaN,NaN,0,32.0,19.0,29.81,0,0,0,0
125706,2025-12-31 23:00,60.0,15.0,NaN,10000.0,1,NaN,NaN,NaN,0,30.0,19.0,29.83,0,0,0,0

In [144]:
percent = (data["limited_visibility"].sum() / len(data)) * 100
percent

1.3260995807711582

In [146]:
mean = data["limited_visibility"].mean()
mean * 100

1.3260995807711582

In [152]:
from datetime import datetime, timedelta

today = datetime.now()
date = today + timedelta(days=60)
today, date

(datetime.datetime(2026, 3, 13, 19, 41, 11, 570494),
 datetime.datetime(2026, 5, 12, 19, 41, 11, 570494))